### PR TITLE
clarify definition

### PR DESCRIPTION
**Pull request by jbasney**
Proposed clarification for the definition statement:
- "it" -> "the identity provider"
- "by or" on its own bullet is unclear, so combine bullets into a single sentence, using parentheses and commas for clarity

### CODE REVIEW

**Comment by nckroy** [comment]
I agree

**Comment by iay** [comment]
Definite improvement in clarity. Might be able to do even better, though, by breaking up what is becoming a really long sentence by inserting a term and breaking off the definition of that term. For example, something like:

> An identity provider MUST NOT be annotated with the academia entity category unless the identity provider is being operated by (or on behalf of and by contract with) at least one _academic organization_.
> 
> Such an academic organization MUST be represented by a legal entity in good standing in the community of other academic organization, fulfilling at least one of the criteria below:

**Comment by nicoleharris** [comment]
I've added this to the refeds forked version

**Comment by leifj** [comment]
if somebody could update this PR to fix the conflict I'll merge

**Comment by leifj** [comment]
still conflicting...

**Comment by nicoleharris** [comment]
I've dealt with this in my proposed changes so you can probably delete this request

**Pull request closed without merging**
